// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhsqhtafaupnyptqwfzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxoc3FodGFmYXVwbnlwdHF3ZnpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4Mjc2OTUsImV4cCI6MjA2ODQwMzY5NX0.c3Sx3Pel0-LwtpFpEEC9Psar9GxyRSp3ys3SrJtM9lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});